$token = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXBlcmFkbWluIiwicm9sZXMiOlsiUk9MRV9TSElQUEVSIiwiUk9MRV9BRE1JTiIsIlJPTEVfQ1VTVE9NRVIiLCJST0xFX1NUQUZGIl0sImlhdCI6MTc3OTg3MjA2MSwiZXhwIjoxNzc5OTU4NDYxfQ._IGuK0NNWQM4H1VlU3-yy-l_3hOKkAelTNKUZbi5_zs'
$headers = @{ Authorization = "Bearer $token"; 'Content-Type' = 'application/json' }
$products = @(
    @{ name = 'Seoul Street Hoodie'; description = 'Soft fleece hoodie with modern Korean streetwear details.'; shortDescription = 'Classic streetwear hoodie'; imageUrl = 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f'; price = 490000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 1; slug = 'seoul-street-hoodie'; sku = 'KF-HOOD-001'; style = 'Street'; season = 'Winter'; gender = 'Unisex'; featured = $true; newArrival = $true },
    @{ name = 'Minimal Logo Hoodie'; description = 'Minimalist hoodie with subtle logo detail and relaxed fit.'; shortDescription = 'Minimal logo hoodie'; imageUrl = 'https://images.unsplash.com/photo-1521334884684-d80222895322'; price = 520000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 1; slug = 'minimal-logo-hoodie'; sku = 'KF-HOOD-002'; style = 'Minimal'; season = 'Fall'; gender = 'Unisex' },
    @{ name = 'Soft Knit Hoodie'; description = 'Lightweight knit hoodie for layering in cool weather.'; shortDescription = 'Soft knit hoodie'; imageUrl = 'https://images.unsplash.com/photo-1512438728091-7f0fcf33b2b3'; price = 470000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 1; slug = 'soft-knit-hoodie'; sku = 'KF-HOOD-003'; style = 'Casual'; season = 'Spring'; gender = 'Women' },
    @{ name = 'K-Pop Varsity Hoodie'; description = 'Varsity-inspired hoodie with contrast sleeves and logo patch.'; shortDescription = 'Varsity style hoodie'; imageUrl = 'https://images.unsplash.com/photo-1512258282477-3f36c0f2c441'; price = 550000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 1; slug = 'kpop-varsity-hoodie'; sku = 'KF-HOOD-004'; style = 'Sporty'; season = 'Fall'; gender = 'Men' },
    @{ name = 'Oversized Loopback Hoodie'; description = 'Oversized hoodie with loopback cotton and soft handfeel.'; shortDescription = 'Oversized loopback hoodie'; imageUrl = 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c'; price = 510000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 1; slug = 'oversized-loopback-hoodie'; sku = 'KF-HOOD-005'; style = 'Relaxed'; season = 'Winter'; gender = 'Unisex' },
    @{ name = 'Floral Midi Dress'; description = 'Flowy floral midi dress with ruffle details.'; shortDescription = 'Floral midi dress'; imageUrl = 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1'; price = 650000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 2; slug = 'floral-midi-dress'; sku = 'KF-DRS-001'; style = 'Romantic'; season = 'Spring'; gender = 'Women' },
    @{ name = 'Pleated Shirt Dress'; description = 'Pleated shirt dress with waist tie and breathable fabric.'; shortDescription = 'Pleated shirt dress'; imageUrl = 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?crop=entropy&cs=tinysrgb&fit=max'; price = 620000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 2; slug = 'pleated-shirt-dress'; sku = 'KF-DRS-002'; style = 'Casual'; season = 'Summer'; gender = 'Women' },
    @{ name = 'Wrap Satin Dress'; description = 'Elegant wrap dress in satin finish for special occasions.'; shortDescription = 'Wrap satin dress'; imageUrl = 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?crop=entropy&cs=tinysrgb&fit=max'; price = 780000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 2; slug = 'wrap-satin-dress'; sku = 'KF-DRS-003'; style = 'Evening'; season = 'Fall'; gender = 'Women' },
    @{ name = 'Layered Tulle Dress'; description = 'Lightweight layered tulle dress with a feminine silhouette.'; shortDescription = 'Layered tulle dress'; imageUrl = 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?ixlib=rb-4.0.3'; price = 830000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 2; slug = 'layered-tulle-dress'; sku = 'KF-DRS-004'; style = 'Elegant'; season = 'Summer'; gender = 'Women' },
    @{ name = 'Ribbed Slip Dress'; description = 'Soft ribbed slip dress with slim fit and minimalist feel.'; shortDescription = 'Ribbed slip dress'; imageUrl = 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?ixlib=rb-4.0.3'; price = 590000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 2; slug = 'ribbed-slip-dress'; sku = 'KF-DRS-005'; style = 'Minimal'; season = 'Spring'; gender = 'Women' },
    @{ name = 'Linen Button-Up Shirt'; description = 'Breathable linen shirt with clean collar and relaxed fit.'; shortDescription = 'Linen button-up shirt'; imageUrl = 'https://images.unsplash.com/photo-1523381218027-3117c9c0f1c8?crop=entropy&cs=tinysrgb&fit=max'; price = 420000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 3; slug = 'linen-button-up-shirt'; sku = 'KF-SHT-001'; style = 'Smart'; season = 'Summer'; gender = 'Men' },
    @{ name = 'V-Neck Blouse'; description = 'Flowy V-neck blouse with subtle puff sleeves.'; shortDescription = 'V-neck blouse'; imageUrl = 'https://images.unsplash.com/photo-1520975911226-8d0bc43a4d16?crop=entropy&cs=tinysrgb&fit=max'; price = 450000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 3; slug = 'v-neck-blouse'; sku = 'KF-SHT-002'; style = 'Feminine'; season = 'Spring'; gender = 'Women' },
    @{ name = 'Oversized Denim Shirt'; description = 'Denim shirt jacket with oversized shoulders and pocket details.'; shortDescription = 'Oversized denim shirt'; imageUrl = 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZGVuaW0lMjBzaGlydHxlbnwwfHwwfHw%3D'; price = 560000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 3; slug = 'oversized-denim-shirt'; sku = 'KF-SHT-003'; style = 'Street'; season = 'Fall'; gender = 'Unisex' },
    @{ name = 'Polka Dot Shirt'; description = 'Classic polka dot shirt with slim cuffs and button closure.'; shortDescription = 'Polka dot shirt'; imageUrl = 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8cG9sa2ElMjBzaGlydHxlbnwwfHwwfHw%3D'; price = 430000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 3; slug = 'polka-dot-shirt'; sku = 'KF-SHT-004'; style = 'Casual'; season = 'Spring'; gender = 'Women' },
    @{ name = 'Stripe Collar Shirt'; description = 'Smart stripe shirt with contrast collar and neat finish.'; shortDescription = 'Stripe collar shirt'; imageUrl = 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHN0cmlwZSUyMGNvbGxhciUyMHNoaXJ0fGVufDB8fDB8fA%3D%3D'; price = 460000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 3; slug = 'stripe-collar-shirt'; sku = 'KF-SHT-005'; style = 'Preppy'; season = 'Spring'; gender = 'Men' },
    @{ name = 'High-Waist Wide-leg Pants'; description = 'High-waist wide-leg pants with easy drape and clean silhouette.'; shortDescription = 'Wide-leg pants'; imageUrl = 'https://images.unsplash.com/photo-1520975911226-8d0bc43a4d16?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzB8fHBhbnRzfGVufDB8fDB8fA%3D%3D'; price = 520000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 4; slug = 'high-waist-wide-leg-pants'; sku = 'KF-PNT-001'; style = 'Minimal'; season = 'Spring'; gender = 'Women' },
    @{ name = 'Tailored Culottes'; description = 'Tailored culottes with pleats and soft waist detail.'; shortDescription = 'Tailored culottes'; imageUrl = 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?crop=entropy&cs=tinysrgb&fit=max'; price = 580000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 4; slug = 'tailored-culottes'; sku = 'KF-PNT-002'; style = 'Chic'; season = 'Summer'; gender = 'Women' },
    @{ name = 'Slim Fit Trousers'; description = 'Slim fit trousers suitable for work and daily styling.'; shortDescription = 'Slim fit trousers'; imageUrl = 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?crop=entropy&cs=tinysrgb&fit=max'; price = 530000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 4; slug = 'slim-fit-trousers'; sku = 'KF-PNT-003'; style = 'Smart'; season = 'Fall'; gender = 'Men' },
    @{ name = 'Cargo Jogger Pants'; description = 'Cargo joggers with elastic cuffs and utility pockets.'; shortDescription = 'Cargo jogger pants'; imageUrl = 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?crop=entropy&cs=tinysrgb&fit=max'; price = 500000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 4; slug = 'cargo-jogger-pants'; sku = 'KF-PNT-004'; style = 'Sporty'; season = 'Autumn'; gender = 'Men' },
    @{ name = 'Soft Knit Shorts'; description = 'Comfort knit shorts with wide waistband and laid-back feel.'; shortDescription = 'Soft knit shorts'; imageUrl = 'https://images.unsplash.com/photo-1521334884684-d80222895322?crop=entropy&cs=tinysrgb&fit=max'; price = 390000; brand = 'Korea Fashion'; origin = 'Korea'; categoryId = 4; slug = 'soft-knit-shorts'; sku = 'KF-PNT-005'; style = 'Casual'; season = 'Summer'; gender = 'Unisex' }
)
$index = 0
foreach ($product in $products) {
    $index++
    $body = $product | ConvertTo-Json -Depth 10
    try {
        $resp = Invoke-RestMethod -Method Post -Uri 'http://103.173.66.91:3398/api/products' -Headers $headers -Body $body -UseBasicParsing
        Write-Host ('Created product {0}: {1}' -f $index, $resp.data.name)
    } catch {
        Write-Host ('ERROR product {0}: {1}' -f $index, $_.Exception.Message)
        $stream = $_.Exception.Response.GetResponseStream()
        $reader = New-Object System.IO.StreamReader($stream)
        Write-Host $reader.ReadToEnd()
    }
}