package com.shope.kf.infrastructure.api.mapper;

import com.shope.kf.infrastructure.api.dto.request.CreateProductRequest;
import com.shope.kf.infrastructure.api.dto.request.UpdateProductRequest;
import com.shope.kf.infrastructure.api.dto.response.ProductResponse;
import com.shope.kf.domain.model.Product;

public final class ProductApiMapper {
    private ProductApiMapper() {
    }

    public static Product toDomain(CreateProductRequest request) {
        return Product.builder()
                .name(request.getName())
                .description(request.getDescription())
                .shortDescription(request.getShortDescription())
                .imageUrl(request.getImageUrl())
                .price(request.getPrice())
                .brand(request.getBrand())
                .brandId(request.getBrandId())
                .origin(request.getOrigin())
                .categoryId(request.getCategoryId())
                .collectionId(request.getCollectionId())
                .sku(request.getSku())
                .slug(request.getSlug())
                .material(request.getMaterial())
                .fabricComposition(request.getFabricComposition())
                .careInstructions(request.getCareInstructions())
                .fit(request.getFit())
                .style(request.getStyle())
                .occasion(request.getOccasion())
                .length(request.getLength())
                .neckline(request.getNeckline())
                .sleeveLength(request.getSleeveLength())
                .pattern(request.getPattern())
                .gender(request.getGender())
                .season(request.getSeason())
                .countryOfManufacture(request.getCountryOfManufacture())
                .madeIn(request.getMadeIn())
                .warrantyPolicy(request.getWarrantyPolicy())
                .returnPolicy(request.getReturnPolicy())
                .status(request.getStatus())
                .stockQuantity(request.getStockQuantity())
                .featured(request.getFeatured())
                .newArrival(request.getNewArrival())
                .bestSeller(request.getBestSeller())
                .sale(request.getSale())
                .viewCount(request.getViewCount())
                .soldCount(request.getSoldCount())
                .compareAtPrice(request.getCompareAtPrice())
                .costPrice(request.getCostPrice())
                .ratingAverage(request.getRatingAverage())
                .reviewCount(request.getReviewCount())
                .weight(request.getWeight())
                .packageWidth(request.getPackageWidth())
                .packageHeight(request.getPackageHeight())
                .packageLength(request.getPackageLength())
                .publishedAt(request.getPublishedAt())
                .tags(request.getTags())
                .seoTitle(request.getSeoTitle())
                .seoDescription(request.getSeoDescription())
                .seoKeywords(request.getSeoKeywords())
                .seoThumbnailUrl(request.getSeoThumbnailUrl())
                .canonicalUrl(request.getCanonicalUrl())
                .schemaType(request.getSchemaType())
                .robots(request.getRobots())
                .build();
    }

    public static Product toDomain(UpdateProductRequest request) {
        return Product.builder()
                .name(request.getName())
                .description(request.getDescription())
                .shortDescription(request.getShortDescription())
                .imageUrl(request.getImageUrl())
                .price(request.getPrice())
                .brand(request.getBrand())
                .brandId(request.getBrandId())
                .origin(request.getOrigin())
                .categoryId(request.getCategoryId())
                .collectionId(request.getCollectionId())
                .sku(request.getSku())
                .slug(request.getSlug())
                .material(request.getMaterial())
                .fabricComposition(request.getFabricComposition())
                .careInstructions(request.getCareInstructions())
                .fit(request.getFit())
                .style(request.getStyle())
                .occasion(request.getOccasion())
                .length(request.getLength())
                .neckline(request.getNeckline())
                .sleeveLength(request.getSleeveLength())
                .pattern(request.getPattern())
                .gender(request.getGender())
                .season(request.getSeason())
                .countryOfManufacture(request.getCountryOfManufacture())
                .madeIn(request.getMadeIn())
                .warrantyPolicy(request.getWarrantyPolicy())
                .returnPolicy(request.getReturnPolicy())
                .status(request.getStatus())
                .stockQuantity(request.getStockQuantity())
                .featured(request.getFeatured())
                .newArrival(request.getNewArrival())
                .bestSeller(request.getBestSeller())
                .sale(request.getSale())
                .viewCount(request.getViewCount())
                .soldCount(request.getSoldCount())
                .compareAtPrice(request.getCompareAtPrice())
                .costPrice(request.getCostPrice())
                .ratingAverage(request.getRatingAverage())
                .reviewCount(request.getReviewCount())
                .weight(request.getWeight())
                .packageWidth(request.getPackageWidth())
                .packageHeight(request.getPackageHeight())
                .packageLength(request.getPackageLength())
                .publishedAt(request.getPublishedAt())
                .tags(request.getTags())
                .seoTitle(request.getSeoTitle())
                .seoDescription(request.getSeoDescription())
                .seoKeywords(request.getSeoKeywords())
                .seoThumbnailUrl(request.getSeoThumbnailUrl())
                .canonicalUrl(request.getCanonicalUrl())
                .schemaType(request.getSchemaType())
                .robots(request.getRobots())
                .build();
    }

    public static ProductResponse toResponse(Product product) {
        return ProductResponse.builder()
                .id(product.getId())
                .name(product.getName())
                .description(product.getDescription())
                .shortDescription(product.getShortDescription())
                .imageUrl(product.getImageUrl())
                .price(product.getPrice())
                .brand(product.getBrand())
                .brandId(product.getBrandId())
                .origin(product.getOrigin())
                .categoryId(product.getCategoryId())
                .collectionId(product.getCollectionId())
                .sku(product.getSku())
                .slug(product.getSlug())
                .material(product.getMaterial())
                .fabricComposition(product.getFabricComposition())
                .careInstructions(product.getCareInstructions())
                .fit(product.getFit())
                .style(product.getStyle())
                .occasion(product.getOccasion())
                .length(product.getLength())
                .neckline(product.getNeckline())
                .sleeveLength(product.getSleeveLength())
                .pattern(product.getPattern())
                .gender(product.getGender())
                .season(product.getSeason())
                .countryOfManufacture(product.getCountryOfManufacture())
                .madeIn(product.getMadeIn())
                .warrantyPolicy(product.getWarrantyPolicy())
                .returnPolicy(product.getReturnPolicy())
                .status(product.getStatus())
                .stockQuantity(product.getStockQuantity())
                .featured(product.getFeatured())
                .newArrival(product.getNewArrival())
                .bestSeller(product.getBestSeller())
                .sale(product.getSale())
                .viewCount(product.getViewCount())
                .soldCount(product.getSoldCount())
                .compareAtPrice(product.getCompareAtPrice())
                .costPrice(product.getCostPrice())
                .ratingAverage(product.getRatingAverage())
                .reviewCount(product.getReviewCount())
                .weight(product.getWeight())
                .packageWidth(product.getPackageWidth())
                .packageHeight(product.getPackageHeight())
                .packageLength(product.getPackageLength())
                .publishedAt(product.getPublishedAt())
                .tags(product.getTags())
                .seoTitle(product.getSeoTitle())
                .seoDescription(product.getSeoDescription())
                .seoKeywords(product.getSeoKeywords())
                .seoThumbnailUrl(product.getSeoThumbnailUrl())
                .canonicalUrl(product.getCanonicalUrl())
                .schemaType(product.getSchemaType())
                .robots(product.getRobots())
                .build();
    }
}
